import type { Metadata } from "next";
import { Baloo_Bhaijaan_2 } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";


const balooBhaijaan = Baloo_Bhaijaan_2({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"], // all available weights
  variable: "--font-baloo", // optional: for CSS variable usage
  display: "swap",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${balooBhaijaan.className} antialiased`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
